// Generated by scripts/generate-pack-catalog.py; metadata only, no sprite pixels.
#pragma once
#include <string>
namespace snes::catalog {
struct Entry {const char *name; const char *file; const char *hash;};
inline constexpr char BASE_URL[] = "https://raw.githubusercontent.com/zeekens/snes-mari-oclock/03400729f378f8e02f927c812e9439bff8cc1c9a/packs";
inline constexpr Entry ENTRIES[] = {
  {"Ghost House","ghost-house-5153597b60d369d7.scn","5153597b60d369d7eeeecfd9cef06b46e9d6750c8428a07f4eda017eb4762f5b"},
  {"Tide Pool","tide-pool-84e168bf9fd78164.scn","84e168bf9fd781643e59e33d713ee096ee7bdda41d728a2caad3f6e400387cae"},
  {"Lava Fortress","lava-fortress-be52d23e28717e59.scn","be52d23e28717e59da903348a49ff45fbb200691034a0434a99a8a2d8bddd2d4"},
  {"Star Road","star-road-258e165b3fe12bea.scn","258e165b3fe12beaf210b9b5490be6eeb3f15c123fc02d6fd18129e82b6439e0"},
  {"Bonus Room","bonus-room-4f1be26e2a384c86.scn","4f1be26e2a384c8672588d50917662c1a414fb4aaa7b2a7664ce021b4e75e71a"}
};
inline const Entry *find(const std::string &name) {
  for (const auto &entry : ENTRIES) if (name == entry.name) return &entry;
  return nullptr;
}
}
